# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181212_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='ReTweet',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
